language: ruby
bundler_args: --without development
sudo: false
rvm: 2.2.0
before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script:
  - xvfb-run bundle exec rspec --tag ~feature spec
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: o1XfO6+cDrJR2jSGQeh3c8NVDwqCjkmDpOjYik+qwIyIUuzHPw3JBz6cAvxLUqoG0EsSHmtip3NtryjUEWkCRUSHI86HvsKDDoyJJ6JAYDcZ7lalrD4jZ7bvQkyv6Z0TGPmLWb8SWsNejrlpwTvWm4ou+PRRr0XZCKfHLn+fjGo=
  app: i-love-basia
  on:
    repo: pboksz/wedding-site
  run: rake db:migrate
notifications:
  email: false
