transportation:
  - locale: 'views.recommendations.transportation.paragraphs.taxi'
    link:
      name: 'iCar'
      url: 'http://icartaxi.eu'
  - locale: 'views.recommendations.transportation.paragraphs.tram'
    link:
      name: 'Jak Dojade'
      url: 'http://krakow.jakdojade.pl'
hotels:
  - name: 'Grand Hotel'
    url: 'http://www.grand.pl'
    map: 'https://goo.gl/maps/nJ91h'
  - name: 'Hotel Komorowski'
    url: 'http://www.hotelkomorowski.com'
    map: 'https://goo.gl/maps/GPp1G'
  - name: 'Hotel Europejski'
    url: 'http://www.hoteleuropejskikrakow.com'
    map: 'https://goo.gl/maps/1PriX'
  - name: 'Hotel Saski'
    url: 'http://www.hotelsaski.com.pl'
    map: 'https://goo.gl/maps/9xKh0'
  - name: 'Hotel Ibis Budget'
    url: 'http://www.accorhotels.com/gb/hotel-7165-ibis-budget-krakow-stare-miasto/index.shtml'
    map: 'https://goo.gl/maps/yFRnr'

places:
  - name: 'Wawel Castle'
    url: 'http://www.wawel.krakow.pl/en'
    map: 'https://goo.gl/maps/TjFHs'
  - name: 'Wieliczka Salt Mines'
    url: 'http://www.wieliczka-saltmine.com/?__utma=1.900265029.1424099190.1424099190.1424099190.1&__utmb=1.1.10.1424099190&__utmc=1&__utmx=-&__utmz=1.1424099190.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)&__utmv=-&__utmk=129348748'
    map: 'https://goo.gl/maps/os1Hg'
  - name: 'Wisła River'
    url: 'http://en.wikipedia.org/wiki/Vistula'
    map: 'https://goo.gl/maps/uORFb'
  - name: 'Rynek'
    url: 'http://www.krakow.pl'
    map: 'https://goo.gl/maps/UYol1'
  - name: 'Koscioł Mariacki'
    url: 'http://mariacki.com/index.php/en'
    map: 'https://goo.gl/maps/IQXjN'
  - name: 'Cracovia Football Stadium'
    url: 'http://www.cracovia.pl'
    map: 'https://goo.gl/maps/p9Mtg'

shopping:
  - name: 'Galeria Krakówska'
    url: 'http://www.galeriakrakowska.pl'
    map: 'https://goo.gl/maps/K3rpk'
  - name: 'Galeria Kazimierz'
    url: 'http://galeriakazimierz.pl'
    map: 'https://goo.gl/maps/wFVg5'
  - name: 'Bonarka City Center'
    url: 'http://www.bonarkacitycenter.pl'
    map: 'https://goo.gl/maps/qLPaf'
