# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a209ddd29a15f9248542236a0595aff7f11773e9227552eb7d9f9bbc2b1b0d2bffca239e11d94e874d6f2fe43c50dd7b0c1b29074b911d7e389b81c29dd50bb

test:
  secret_key_base: 92456eaa8992764e1b971bc6105223ee39e5784dde9b8f3109f1e4ffaf07593ce3caf0ca4843ca9db92b6da95f908245573598ff7fedab71df596dac7b2823f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
